INSERT INTO ACCOUNT (LOGIN, PASSWORD, EMAIL, PRIVILEGE)
VALUES ('admin', '$2a$10$OvdSbEwvFfpffmybNgjkFOPwAZkgllUjFGLwx.GZRC6HGtP5w7FEK', 'admin@admin.com', 'ADMIN');
INSERT INTO ACCOUNT (LOGIN, PASSWORD, EMAIL, PRIVILEGE)
VALUES ('user1', '$2a$10$udmudsA0mqBS57KNrntMGescvG4P.qB2f834rbX101bDuzXofX/wS', 'user1@user1.com', 'worker');
INSERT INTO ACCOUNT (LOGIN, PASSWORD, EMAIL, PRIVILEGE)
VALUES ('user2', 'user2', 'user2@user2.com', 'beekeeper');
INSERT INTO ACCOUNT (LOGIN, PASSWORD, EMAIL, PRIVILEGE)
VALUES ('user3', 'user3', 'user3@user3.com', 'worker');
INSERT INTO ACCOUNT (LOGIN, PASSWORD, EMAIL, PRIVILEGE)
VALUES ('user4', 'user4', 'user4@user4.com', 'worker');
INSERT INTO APIARY (LOCALIZATION, INFORMATION)
VALUES ('Krakow', 'Some interesting apiary');
INSERT INTO APIARY (INFORMATION)
VALUES ('This one is only for information');
INSERT INTO APIARY (LOCALIZATION)
VALUES ('Lubzina');
INSERT INTO APIARY (LOCALIZATION)
VALUES ('Place');
INSERT INTO "EVENT" (ID_apiary, Time_start, note)
VALUES (1, CURRENT_TIMESTAMP, 'There was event');
INSERT INTO "EVENT" (ID_apiary, Time_start, note)
VALUES (2, CURRENT_TIMESTAMP, 'Apiary under attack!');
INSERT INTO "EVENT" (ID_apiary, Time_start, note)
VALUES (3, CURRENT_TIMESTAMP, 'Bear attacked!');
INSERT INTO APIARY_ACCOUNT (ID_apiary, ID_account)
SELECT 1,
  ID
FROM ACCOUNT
WHERE LOGIN = 'admin';
INSERT INTO APIARY_ACCOUNT (ID_apiary, ID_account)
SELECT 2,
  ID
FROM ACCOUNT
WHERE LOGIN = 'admin';
INSERT INTO APIARY_ACCOUNT (ID_apiary, ID_account)
SELECT 3,
  ID
FROM ACCOUNT
WHERE LOGIN = 'user1';
INSERT INTO EVENT_ACCOUNT (ID_EVENT, ID_ACCOUNT)
VALUES(1, 1);
INSERT INTO EVENT_ACCOUNT (ID_EVENT, ID_ACCOUNT)
VALUES(2, 2);
INSERT INTO EVENT_ACCOUNT (ID_EVENT, ID_ACCOUNT)
VALUES(1, 3);
INSERT INTO EVENT_ACCOUNT (ID_EVENT, ID_ACCOUNT)
VALUES(2, 4);